### ISSUE TITLE
Mixed content : Security issue

### ISSUE THREAD

**Issue by askadu** [Moonly-App/moonly-app#2]
**Value Statement**

```
As a user
I want all resources should serve over _HTTPs_
So that app can be more secure and SEO should not be impacted
and i should see that 'green lock icon on browser address bar'
```
**Requirements**

1. [Must Have] Should not link HTTP resources.

**Technical Approach**
We can use github as a CDN for all your static resource like css, js, images etc. If original server doesn't support SSL.

**Note:**
Now i can see only images are getting served over HTTP protocol
`i.e http://s2.googleusercontent.com/s2/favicons`

**Comment by shtefcs** [comment]
@askadu Had in mind to add that in issue but forgot. Thanks for adding and contributing. Jelena just merged/approved your PR. 

If you want, you can add same thing for Extension over here https://github.com/Moonly-App/moonly-extension

**Comment by shtefcs** [comment]
@jelenajjo we should deploy this to live server, right ?
