### ISSUE TITLE
The Images in the file readme.md has broken links

### ISSUE THREAD

**Issue by charliedua** [Moonly-App/moonly-app#21]
The links in the readme.md which relates to **credit references** and **Contributors** have broken links to profile images.
![image](https://user-images.githubusercontent.com/33629087/48098607-65afc500-e271-11e8-829a-8d7cbac6115c.png)
Moreover there is no alternative text displayed on links to images being broken

### I think the source of this issue might be : 
![image](https://user-images.githubusercontent.com/33629087/48098726-a3145280-e271-11e8-839e-11fc3b35dbd0.png)

### What I did: 
- Copied the image links to check if the image is hosted at that link.
### Observation:
- The link is shows `URL signature expired`

**Comment by shtefcs** [comment]
Fixed https://github.com/Moonly-App/moonly-app/commit/ed13b319b4e484c9ef6c73e2c9b3f158e83d9833
